- name: Variables from the file
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks: 
  - name: print the course info
    ansible.builtin.debug:
      msg: " Course: {{ Course}}, Duration: {{ Duration }}, Trainer: {{ Trainer }}"