- name: Conditions
  hosts: local
  connection: local
  vars:
   number: 5
  tasks:
  - name: Check if number is leass or not
    ansible.builtin.debug:
      msg: "The given number : {{ number }} is less than 10"
    when: number < 10