- name: Transforming string 
  hosts: local
  connection: local
  vars:
    technologies: "ansible, docker, kubernetes, github"
    tags:
      Application: payment
      Environment: dev 
  tasks:
  - name: List of string
    ansible.builtin.debug:
      msg: " List is {{ technologies | split(',') }}"
  
  - name: Dictornary of string
    ansible.builtin.debug:
      msg: " Dictonary is: {{ tags | dict2items }}"
