- name: Transforming string 
  hosts: local
  connection: local
  vars:
  #### STRING ####
    technologies: "ansible, docker, kubernetes, github"
    name: "Pratiksha Gunti"
    email: "Pratiksha.gunti@GMAIL.COM"
    ipaddress: "192.168.0.1"
  #### MAP or Dictionary ####
    tags:
      Application: payment
      Environment: dev 
  #### list of Dictorary ####
    listTags:
    - key: Application
      value: payment
    - key: Environment
      value: dev
  tasks:
  - name: List of string
    ansible.builtin.debug:
      msg: " List is {{ technologies | split(',') }}"
  
  - name: Dictornary of string
    ansible.builtin.debug:
      msg: " Dictonary is: {{ tags | dict2items }}"

  - name: List of MAp to MAp
    ansible.builtin.debug:
      msg: " list is: {{ listTags | items2dict }}"

  - name: read the yaml file into a variables
    ansible.builtin.set_fact:
      student_yaml: "{{ lookup('file', 'student.yaml') | from_yaml }}"
  
  - name: convert the yaml into json
    ansible.builtin.debug:
      msg: "json: {{ student_yaml | to_json }}"
  
  - name: copy the content from student_yaml to file
    ansible.builtin.copy:
      dest: ./student-data.json
      content: "{{ student_yaml | to_nice_json }}"
  
  - name: convert into uppercase
    ansible.builtin.debug:
      msg: "{{ name | upper }}"

  - name: convert into lowercase
    ansible.builtin.debug:
      msg: "{{ email | lower }}"

  - name: Validating IP addresses
    ansible.builtin.debug: "{{ ipaddress | ansible.utils.ipv4 }}"

